hrms/Employee/urls.py
from django.urls import path
from django.conf.urls import url
from .import views
app_name = 'Employee'
urlpatterns=[
    url('dashbord',views.dash_Bord ,name= 'dashbord'),
    path('index',views.index,name='index'),
    path('register',views.add_Employee,name='regsiter'),
    path('changepass',views.changePassw,name='changepass'),
    path('show',views.updateinfo,name='show_data'),
    # path('edit/', views.employeeEdit, name='edit_emp'),
    # path('delete/<int:id>/', views.employeeDelete, name='del_emp'),
    path('edit/<int:id>/', views.edit, name='emp_edit'),
    path('delete/<int:id>/',views.delete, name='emp_delete'),
    path('emp_download',views.download, name='emp_download'),
    path('userlog/', views.index),

]

hrms/hrms/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('webcloud/', admin.site.urls),
    path('',include('Employee.urls',namespace='Employee')),
    path('',include('leave.urls')),
    path('',include('account.urls')),
    path('',include('Salary.urls')),
    path('', include('django.contrib.auth.urls')),

]

admin.site.site_header='WELCOME TO WEB CLOUD TECHNOLOGY '
admin.site.index_title='Welcome To Web Cloud Technology Human Resource Management'

hrms/Employee/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Employee(models.Model):
    GENDER_CHOICES = (
        ('', 'Select Gender'),
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    Depart_Choice=(

        ('','Select Your Department'),
        ('Web Design & Development','Web Design & Development'),
        ('Digital Marketing','Digital Marketing'),
        ('Sales Team','Sales Team'),
        ('Human Resource','Human Resource'),
        ('Other','Other'),
    )
    Laptop_Choice=(
        ('','Office Laptop'),
        ('y','Yes'),
        ('n','No')
    )
    Blood_Choice=(
        ('','Blood Group'),
        ('O+','O+'),
        ('O-','O-'),
        ('B+','B+'),
        ('B-','B-'),
        ('A+','A+'),
        ('A-','A-'),
        ('AB+','AB+'),
        ('Ab-','AB-'),

    )
    name=models.CharField(max_length=100)
    code=models.CharField(max_length=50,)
    mobile=models.IntegerField(unique=True)
    address=models.TextField()
    gender =models.CharField(choices=GENDER_CHOICES, max_length=8)
    email =models.EmailField(unique=True)
    blood_group=models.CharField(choices=Blood_Choice,max_length=50)
    department=models.CharField(choices=Depart_Choice,max_length=100)
    designation=models.CharField(max_length=100)
    laptop=models.CharField(choices=Laptop_Choice,max_length=10)
    salary=models.CharField(max_length=100,default='0000..')
    password=models.CharField(max_length=100)

    # class Meta:
    #     managed = True
    #     db_table='employee'
    def __str__(self):
        return self.name

hrms/Employee/forms.py
from django import forms
from .models import Employee
class Emp_LoginForm(forms.ModelForm):
    class Meta:
        model=Employee
        fields=[
            'email','password'
        ]

class PasswordChangeForms(forms.ModelForm):
    class Meta:
        model=Employee
        fields=[
             'email','password'
        ]
        widgets = {
            'password': forms.PasswordInput(),
        }







class NewEmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields =['name','mobile','address','gender','email','blood_group','department','designation','laptop','password']
        widgets = {
            'password': forms.PasswordInput(),
        }


class changePasswordForm(forms.Form):
     oldPassword=forms.CharField(label='Enter Old Password',max_length=50 ,min_length=5)
     newpassword1=forms.CharField(label='Enter New Updated Password',max_length=50,min_length=5)
     newpassword2=forms.CharField(label='Repeat Your New Password',max_length=50,min_length=5)

hrms/Employee/views.py
from django.shortcuts import render,redirect,HttpResponse
from .models import Employee
import csv
from django.contrib import messages
from .forms import NewEmployeeForm,changePasswordForm,Emp_LoginForm
from django.http import FileResponse
from django.contrib.auth import update_session_auth_hash
from .forms import PasswordChangeForms
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login
def add_Employee(request):
    form=NewEmployeeForm(request.POST or None)
    if form.is_valid():
        form.save()
        print('hellow')
    context={
        'form':form
    }
    return render(request,'adduser.html',context)
# Create your views here
def dash_Bord(request):
    emp = request.session.get('emp')
    digital= Employee.objects.filter(department='Digital Marketing').count()
    webde= Employee.objects.filter(department='Web Design & Development').count()
    sales= Employee.objects.filter(department='Sales Team').count()
    hr= Employee.objects.filter(department='Human Resource').count()
    context={'webdevelopment':webde,'sales':sales,'degital':digital,'hr':hr}
    return render(request,'dashboard/dashboard_index.html',context)

def index(request):
    if request.method=='POST':
        uid=request.POST.get('email')
        passw=request.POST.get('psw')
        user=Employee.objects.filter(email=uid,password=passw)
        if user:
            request.session['emp']=passw
            request.session['email']=uid
            return redirect('/dashbord')
        else:

            return render(request, 'index.html')

    return render(request,'index.html')

def download(request):
    resopnce = HttpResponse(content_type='text/csv')
    resopnce['Content-Disposition'] = 'attachment; filename=WCTEmployee.csv'
    writer = csv.writer(resopnce)
    writer.writerow(['Name','Code','Mobile','Address','Gender','Email','Blood Group','Department'
                     'Designation','Laptop','salary'])
    emp = request.session.get('emp')
    empdata = Employee.objects.all().filter(password=emp)
    for data in empdata:
        writer.writerow([data.name,data.code,data.mobile,data.address,data.gender,
                         data.blood_group,data.department,data.designation,data.laptop,data.salary])

    return resopnce
def changePassw(request):
    if request.method == 'POST' or None:
            name=request.POST.get('uname')
            pass1=request.POST.get('psw')
            pass2=request.POST.get('psw1')
            user=Employee.objects.filter(name=name)and pass1==pass2
            if user:

                messages.success(request,'Password Updated Successfully !')
                return redirect('/userlog')
            else:
                messages.error(request,'Pleae Enter Currect Info')
                return redirect('/changepass')

    else:
         return render(request, 'changepass.html')

def updateinfo(request):
    emp = request.session.get('emp')
    empdata=Employee.objects.all().filter(password=emp)
    context={'all_employee':empdata}
    return render(request,'update.html',context)

def edit(request,id):
    empObj =Employee.objects.get(pk=id)
    form =NewEmployeeForm(request.POST or None, instance=empObj)
    if form.is_valid():
        form.save()
        return redirect('/show')
    context ={
       'form':form
    }
    return render(request,'edit.html',context)

def delete(request,id):
        obj = Employee.objects.get(id=id)
        obj.delete()
        return redirect('login')

def user_login(request):
  pass

hrms/Employee/templates/add_employee.html
{% extends 'dashboard/base.html'%}
{% load static %}
<link href="{% static 'assets/css/bootstrap.min.css'%}" rel="stylesheet"/>
{% block body %}
<div class="box">
    <div class="container">
        <a href="/logout"  class="btn btn-info btn-lg">Logout</a>
        <a href="changepass"  class="btn btn-info btn-lg">Change Password</a>
        <h1 class="text-center">Add Yours Details</h1>
        <div class="customer_box">
            <form method="post" id="add_customer">
                {%csrf_token%}
                {% for field in form %}
                <div class="col-md-6">

                    <div class="form-group">

                        <label>{{ field.label_tag }}</label>
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}


                        {% endif %}
                    </div>
                </div>
                {% endfor %}
                <div class="col-md-6">
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-lg">Add Your Details</button>
                        <a href="dashbord"  class="btn btn-info btn-lg">Back</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

hrms/Employee/templates/adduser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

hrms/Employee/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>EMS Project </title>
  <meta charset="utf-8">
  <link href="https://fonts.googleapis.com/css?family=Arvo|Teko&display=swap" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
  <script src="{% static 'js/jquery.js'%}"></script>
  <script src="{% static 'js/bootstrap.js'%}"></script>
  <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>-->
  <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>-->
</head>
<body>

<style>
  body{
  font-family: 'Arvo', serif;
  }
  .is_invalid{
  border:solid 1px red;
  }
  .is_invalid_text{
  color: red;
    float: left;
    border: 0;
    padding: 0;
    position: absolute;
    list-style: none;
    left: 5%;
  }
  .is_valid{
  border:solid 1px green;
  }
  .box{
  background: #eeeeee;
  padding: 10px;
  }

  .delete{
  background: #147c82;
    width: 42%;
    margin: auto;
    padding: 20px;
    color: #fff;
  }
  .customer_box{
    margin-top: 5%;
    color: #207740;
    text-transform: uppercase;
  }

  .box h1{
      background: #e2dcdc;
    padding: 6px;
    border-radius: 5px;
  }
  .allCityWrap{
    position:relative;
  }

  .citylist{
    background: #fff;
    padding: 6px;
    border-radius: 4px;
    border-bottom: solid 1px #ddd;
    cursor:pointer;
  }


  #allCity{
      position: absolute;
      width: 95%;

  }

</style>
{% block content %}
{% endblock%}


<script>
    $(document).ready(function(){
        $('input').addClass('form-control');
        $('select').addClass('form-control');
        $("#id_city").wrap('<div id="allCityWrap"></div>');
        $('input').attr('autocomplete','off');
        $('.errorlist').addClass('is_invalid_text');
        $("#id_city").after('<div id="allCity"></div>');
        $(".editdiv #id_age").attr("disabled",true);








    $('#id_name').keypress(function (e) {
        var regex = new RegExp(/^[a-zA-Z\s]+$/);
        var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
        if (regex.test(str)) {
          $('#id_name').focus();
        }
        else {
            e.preventDefault();
            return false;
        }
    });


    function checkPanNumer(){

        var regex = /([A-Z]){5}([0-9]){4}([A-Z]){1}$/;
        var panid =$("#id_pan_number").val().toUpperCase();
            if (regex.test(panid)) {
                $("#id_pan_number").css('border','solid 1px green');

            } else {
               $("#id_pan_number").addClass('is_invalid');
                return false;
            }
    }
    $('#id_pan_number').change(function () {
       checkPanNumer();

    });

    $('#id_pan_number').keyup(function () {
       upper_text =$("#id_pan_number").val().toUpperCase();
       $("#id_pan_number").val(upper_text);

    });


    function ageLimit(){
        $("id_age").attr('max','100');
       id_age =$("#id_age").val();
       limitText=parseInt(id_age);

       if (limitText<1 || limitText>100){
        $("#id_age").addClass('is_invalid');

       }
       else{
        //$("#id_age").css('border','solid 1px green');
       return false;
       }

    }

    $('#id_age').keyup(function () {
        ageLimit();

    });

    function emailValidChech(){
      debugger;
        var regex = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
        var panid =$("#id_email").val();
            if (regex.test(panid)) {
                $("#id_email").css('border','solid 1px green');
                $("#id_email").focus();

            } else {
               $("#id_email").addClass('is_invalid');
                return false;
            }
    }



    $('#id_email').keyup(function () {
      emailValidChech();
    });






});


</script>
<script>
  function btnHandle(gcity){
      debugger;
      $('#id_city').val(gcity.innerText);
      $("#allCity").hide();
      }

  $('#id_city').keyup(function () {
    selectCity =$('#id_city').val();
    $("#allCity").show()
    $("#allCity").html('');
      $.ajax({
            url:"",
            type:"get",

            data:{selectCity:selectCity},
            success:function(data){

              for (i=0; i<=5; i++){
                $("#allCity").append('<div class="citylist" onclick="btnHandle(this)">'+data[i].fields.name+'</div>')
                   }


            }

      });


    });
</script>
</body>
</html>

hrms/Employee/templates/changepass.html
<html>
{% load static %}
<header>
    <title>WCT-HRMS</title>
    <link href="{% static 'assets/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/mystyle.css'%}" rel="stylesheet">
</header>
<body>
<div class="container">


    <div class="myform">


        <form method="post" novalidate>

            {% if messages %}
   {% for message in messages %}
    <h6 style="color:red;" {% if message.tags%} class="{{message.tags}}"{% endif %}
    >{{message}}</h6>
   {% endfor%}

{% endif%}
        {% csrf_token %}
    <img src="{% static 'assets/images/webc.png'%}" alt="WCT" class="avatar">

  {% csrf_token %}
  <div class="container">
    <label for="uname"><b>Username</b></label><br>
    <input type="text" placeholder="Enter Name" name="uname" required><br>

    <label for="psw"><b>New Password</b></label><br>
    <input type="password" placeholder="Enter Password" name="psw" required>
    <br>
    <label for="psws"><b>Re_Enter Password</b></label><br>
    <input type="password" placeholder="Enter Password" name="psw1" required><br>

        <div class="button">
            <button type="submit" class="btn btn-success">Save</button>
            <a href="dashbord" class="btn btn-primary">Back</a>
        </div>
           {% if form.non_field_errors %}
               {% for error in form.non_field_errors %}
            <div class="group">
            <p style="color:red"><b>{{error}}</b></p>
            </div>
               {% endfor%}
            {% endif %}
        </form>
        {{data}}
    </div>
</div>
</body>
</html>

hrms/Employee/templates/edit.html
{% extends 'base2.html'%}

{% block content %}
<div class="box">
    <div class="container">
        <h1 class="text-center">Update Your Information</h1>
        <div class="customer_box editdiv">
        <form method="post">
            {%csrf_token%}
            {% for field in form %}
            <div class="col-md-4">

                <div class="form-group">
                    <label>{{ field.label_tag }}</label>
                    {{ field }}
                    {{ field.errors }}
                    {% if field.help_text %}

                    {% endif %}
                </div>
            </div>
            {% endfor %}
            <div class="col-md-1">
                <div class="form-group">
                    <button type="submit" class="btn btn-success btn-lg">Edit Customer</button>
                    <a href="#"  class="btn btn-info btn-lg">Back</a>
                </div>
            </div>

        </form>
        </div>
    </div>
</div>
{% endblock%}

hrms/Employee/templates/update.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <meta name="description" content=""/>
  <meta name="author" content=""/>
  <title>Emp</title>

    <!-- loader-->
  <!--<link href="assets/css/pace.min.css" rel="stylesheet"/>
  <script src="assets/js/pace.min.js"></script>-->


  <link rel="icon" href="{% static 'assets/images/favicon.ico'%}" type="image/x-icon">
  <!-- simplebar CSS-->
  <link href="{% static 'assets/plugins/simplebar/css/simplebar.css'%}" rel="stylesheet"/>
  <!-- Bootstrap core CSS-->
  <link href="{% static 'assets/css/bootstrap.min.css'%}" rel="stylesheet"/>
  <!--Data Tables -->
  <link href="{% static 'assets/plugins/bootstrap-datatable/css/dataTables.bootstrap4.min.css'%}" rel="stylesheet" type="text/css">
  <link href="{% static 'assets/plugins/bootstrap-datatable/css/buttons.bootstrap4.min.css'%}" rel="stylesheet" type="text/css">
  <!-- animate CSS-->
  <link href="{% static 'assets/css/animate.css'%}" rel="stylesheet" type="text/css"/>
  <!-- Icons CSS-->
  <link href="{% static 'assets/css/icons.css'%}" rel="stylesheet" type="text/css"/>
  <!-- Metismenu CSS-->
  <link href="{% static 'assets/plugins/metismenu/css/metisMenu.min.css'%}" rel="stylesheet"/>
  <!-- Custom Style-->
  <link href="{% static 'assets/css/app-style.css'%}" rel="stylesheet"/>
    <link href="{% static 'css/style.css'%}" rel="stylesheet"/>
</head>

<body class="bg-theme bg-theme1">
{% if messages %}
   {% for message in messages %}
    <small {% if message.tags%} class="{{message.tags}}"{% endif %}
    >{{message}}</small>
   {% endfor%}

{% endif%}

<!-- Start wrapper-->
 <div id="wrapper">

     <div id="sidebar-wrapper" data-simplebar="" data-simplebar-auto-hide="true">

    <div class="brand-logo">
	  <img src="{% static 'assets/images/webc.png'%}" class="logo-icon" alt="logo icon">
	  <h5 class="logo-text">WCT Employee</h5>
	  <div class="close-btn"><i class="zmdi zmdi-close"></i></div>
   </div>
     <ul class="metismenu" id="menu">
     	<li><a href="dashbord"><div class="parent-icon"><i class="zmdi zmdi-view-dashboard"></i></div><div class="menu-title">Dashboard</div></a></li>
		<li><a href="wctemp"><div class="parent-icon"><i class='zmdi zmdi-coffee'></i></div><div class="menu-title">Basic Info</div></a></li>
         <li><a href="show"><div class="parent-icon"><i class='zmdi zmdi-coffee'></i></div><div class="menu-title">Show Detalis</div></a></li>
         <li><a href="leave"><div class="parent-icon"><i class='zmdi zmdi-coffee'></i></div><div class="menu-title">Leave</div></a></li>
         <li><a href="account"><div class="parent-icon"><i class='zmdi zmdi-coffee'></i></div><div class="menu-title">Add Bank Info</div></a></li>
         <li><a href="payslip"><div class="parent-icon"><i class='zmdi zmdi-coffee'></i></div><div class="menu-title">payslip</div></a></li>
     </ul>
        <ul>
          <li class="list-group-item text-center"><a href="javaScript:void();">See All Messages</a></li>
        </ul>
        </div>



<!--End topbar header-->
<div class="clearfix"></div>

  <div class="content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-header"><i class="fa fa-table"></i> Hello {{name}} Welcome to Web cloud Technology</div>
            <div class="card-body">
              <div class="table-responsive">
                  <table id="example" class="table table-bordered">

              <thead class="bg-primary text-white">
        <tr>
            <th>Name</th>
            <th>Code</th>
            <th>Mobile</th>
            <th>Address</th>
            <th>Gender</th>
            <th>Email</th>
            <th>Blood Group</th>
            <th>Department</th>
            <th>Designatio</th>
            <th>Laptop</th>
            <th>salary</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody id="emp_table">
        {% for emp in all_employee %}
        <tr>
            <th>{{emp.name}}</th>
            <th>{{emp.code}}</th>
            <th>{{emp.mobile}}</th>
            <th>{{emp.address}}</th>
            <th>{{emp.gender}}</th>
            <th>{{emp.email}}</th>
            <th>{{emp.blood_group}}</th>
            <th>{{emp.department}}</th>
            <th>{{emp.designation}}</th>
            <th>{{emp.laptop}}</th>
            <th>{{emp.salary}}</th>
            <th><a href="{% url 'Employee:emp_edit' emp.id %}">Edit</a>
               <a href="{% url 'Employee:emp_delete' emp.id %}">Delete</a>
                <a href="emp_download">download</a>
            </th>
        </tr>
{% endfor%}

        <tfoot>


        <td colspan="8">
            {% if all_employee.has_other_pages %}
            <ul class="pagination">
                {% if all_employee.has_previous %}
                <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
                {% else %}
                <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in all_employee.paginator.page_range %}
                {% if all_employee.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if all_employee.has_next %}
                <li><a href="?page={{ users.next_page_number }}">&raquo;</a></li>
                {% else %}
                <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
            {% endif %}
        </td>

        </td>
        </tfoot>
        </tbody>


    </table>
            </div>
            </div>
          </div>
        </div>
      </div><!-- End Row-->
<!--start overlay-->
	  <div class="overlay"></div>
	<!--end overlay-->
    </div>

    </div>
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>


    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>

<footer class="footer">
      <div class="container">
        <div class="text-center">
          Copyright © 2020 | Powered By <strong><a href="http://www.webcloudtechnologies.com/" target="_blank" style="text-decoration: underline;">Web Cloud Technologies.</a>
        </div>
      </div>
</footer>  </div>


     <script src="{% static 'assets/js/jquery.min.js'%}"></script>
  <script src="{% static 'assets/js/popper.min.js'%}"></script>
  <script src="{% static 'assets/js/bootstrap.min.js'%}"></script>

  <!-- simplebar js -->
  <script src="{% static 'assets/plugins/simplebar/js/simplebar.js'%}"></script>
  <!-- Metismenu js -->
  <script src="{% static 'assets/plugins/metismenu/js/metisMenu.min.js'%}"></script>

  <!-- Custom scripts -->
  <script src="{% static 'assets/js/app-script.js'%}"></script>

  <!--Data Tables js-->
  <script src="{% static 'assets/plugins/bootstrap-datatable/js/jquery.dataTables.min.js'%}"></script>
  <script src="{% static 'assets/plugins/bootstrap-datatable/js/dataTables.bootstrap4.min.js'%}"></script>
  <script src="{% static 'assets/plugins/bootstrap-datatable/js/dataTables.buttons.min.js'%}"></script>
  <script src="{% static 'assets/plugins/bootstrap-datatable/js/buttons.bootstrap4.min.js'%}"></script>
  <script src="{% static 'assets/plugins/bootstrap-datatable/js/jszip.min.js'%}"></script>
  <script src="{% static 'assets/plugins/bootstrap-datatable/js/pdfmake.min.js'%}"></script>
  <script src="{% static 'assets/plugins/bootstrap-datatable/js/vfs_fonts.js'%}"></script>
  <script src="{% static 'assets/plugins/bootstrap-datatable/js/buttons.html5.min.js'%}"></script>
  <script src="{% static 'assets/plugins/bootstrap-datatable/js/buttons.print.min.js'%}"></script>
  <script src="{% static 'assets/plugins/bootstrap-datatable/js/buttons.colVis.min.js'%}"></script>

    <script>
     $(document).ready(function() {
      //Default data table
       $('#default-datatable').DataTable();


       var table = $('#example').DataTable( {
        lengthChange: false,
        buttons: [ 'copy', 'excel', 'pdf', 'print', 'colvis' ]
      } );

     table.buttons().container()
        .appendTo( '#example_wrapper .col-md-6:eq(0)' );

      } );

    </script></body>
</html>